from datetime import date
from io import BytesIO

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import Response
from fpdf import FPDF

from src.api.deps import get_current_user, get_pool
from src.api.models import AccountDetail, AccountRow, MonthlyPoint, ServiceRow
from src.db import queries

router = APIRouter()


def _first_of_month(d: date) -> date:
    return d.replace(day=1)


def _prev_month(d: date) -> date:
    if d.month == 1:
        return date(d.year - 1, 12, 1)
    return date(d.year, d.month - 1, 1)


@router.get("/accounts", response_model=list[AccountRow])
async def list_accounts(_user=Depends(get_current_user)):
    today = date.today()
    rows = await queries.list_accounts_with_recent_totals(
        get_pool(), _first_of_month(today), _prev_month(_first_of_month(today))
    )
    return rows


@router.get("/accounts/{account_id}", response_model=AccountDetail)
async def get_account(account_id: str, _user=Depends(get_current_user)):
    pool = get_pool()
    acct = await queries.get_account(pool, account_id)
    if acct is None:
        raise HTTPException(404, "Account not found")
    monthly = await queries.get_monthly_series(pool, account_id, months=12)
    return AccountDetail(
        **acct,
        monthly=[MonthlyPoint(**m) for m in monthly],
    )


def _parse_month(month: str) -> date:
    try:
        year, mon = map(int, month.split("-"))
        return date(year, mon, 1)
    except ValueError:
        raise HTTPException(400, "month must be YYYY-MM")


@router.get("/accounts/{account_id}/services", response_model=list[ServiceRow])
async def get_account_services(
    account_id: str,
    month: str = Query(..., description="YYYY-MM"),
    _user=Depends(get_current_user),
):
    month_date = _parse_month(month)
    services = await queries.get_services(get_pool(), account_id, month_date)
    total = sum(s["cost_usd"] for s in services if s["cost_usd"] > 0) or 1
    return [
        ServiceRow(
            service=s["service"],
            cost_usd=s["cost_usd"],
            pct=s["cost_usd"] / total * 100,
            usage_qty=s.get("usage_qty"),
            usage_unit=s.get("usage_unit"),
        )
        for s in services
    ]


@router.get("/accounts/{account_id}/services.pdf")
async def get_account_services_pdf(
    account_id: str,
    month: str = Query(..., description="YYYY-MM"),
    _user=Depends(get_current_user),
):
    month_date = _parse_month(month)
    pool = get_pool()
    acct = await queries.get_account(pool, account_id)
    if acct is None:
        raise HTTPException(404, "Account not found")
    services = await queries.get_services(pool, account_id, month_date)
    services = [s for s in services if s["cost_usd"] > 0]
    services.sort(key=lambda s: s["cost_usd"], reverse=True)
    total = sum(s["cost_usd"] for s in services) or 0.0

    pdf = FPDF(unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "AWS Cost Report", ln=True)

    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, acct["name"], ln=True)
    billing_label = "consolidated" if acct["billing"] == "org" else "separate invoice"
    pdf.set_text_color(110, 110, 110)
    pdf.cell(0, 5, f"{acct['account_id']} - {billing_label}", ln=True)
    pdf.cell(0, 5, f"Period: {month_date.strftime('%B %Y')}", ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, f"Total: ${total:,.2f} USD", ln=True)
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(78, 7, "Service", border=1, fill=True)
    pdf.cell(45, 7, "Usage", border=1, align="R", fill=True)
    pdf.cell(30, 7, "Cost (USD)", border=1, align="R", fill=True)
    pdf.cell(27, 7, "% of total", border=1, align="R", fill=True, ln=True)

    pdf.set_font("Helvetica", "", 10)
    if not services:
        pdf.cell(180, 7, "No costs recorded for this month.", border=1, align="C", ln=True)
    else:
        for s in services:
            pct = (s["cost_usd"] / total * 100) if total else 0.0
            qty = s.get("usage_qty")
            unit = s.get("usage_unit")
            usage_label = f"{qty:,.2f} {unit}" if qty is not None and unit else ""
            pdf.cell(78, 6, s["service"][:48], border=1)
            pdf.cell(45, 6, usage_label, border=1, align="R")
            pdf.cell(30, 6, f"${s['cost_usd']:,.2f}", border=1, align="R")
            pdf.cell(27, 6, f"{pct:.1f}%", border=1, align="R", ln=True)

    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(140, 140, 140)
    pdf.cell(
        0,
        4,
        "Generated by aws.mees.st - figures from AWS Cost Explorer (UnblendedCost).",
        ln=True,
    )

    buf = BytesIO()
    pdf.output(buf)
    filename = f"aws-billing-{acct['slug']}-{month}.pdf"
    return Response(
        content=buf.getvalue(),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
